analyzer:
  errors:
    missing_required_param: error
    todo: ignore
    fixme: warning
    invalid_use_of_visible_for_testing_member: error

  plugins:
    - custom_lint  

include: package:flutter_lints/flutter.yaml

custom_lint:
  enable_all_lint_rules: false
  rules:
    - fixed_text_scale_rich_text: true
    - defined_void_callback_type: true
    - defined_value_setter_type: true
    - defined_value_getter_type: true
    - defined_value_changed_type: true
    - defined_async_value_setter_type: true
    - defined_async_value_getter_type: true
    - defined_async_callback_type: true


linter:
  rules:
    - always_use_package_imports
    - always_put_required_named_parameters_first
    - annotate_redeclares
    - avoid_annotating_with_dynamic
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - cancel_subscriptions
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - file_names
    - hash_and_equals
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - non_constant_identifier_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - sort_pub_dependencies
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_is_even_rather_than_modulo
    - valid_regexps
    - void_checks
    - unnecessary_await_in_return
    - prefer_expression_function_bodies
    - unnecessary_underscores
    - use_decorated_box
    - cascade_invocations
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - sized_box_shrink_expand
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_fields
    - prefer_final_in_for_each
    - sort_unnamed_constructors_first
    - prefer_null_aware_method_calls
    - avoid_redundant_argument_values
    - no_literal_bool_comparisons
    - unnecessary_breaks
    - matching_super_parameters
    - unawaited_futures