name: secret_hitler_companion
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  audioplayers: ^6.5.1
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_fy:
    git:
      url: https://github.com/danieldcastro/flutter_fy.git
      ref: 0.1.11
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.4.1
  intl: ^0.20.2
  lottie: ^3.3.2
  lucide_icons_flutter: ^3.1.1
  nilts: ^0.24.0
  shared_preferences: ^2.5.3
  vibration: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  melos: ^7.1.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Eskapade Fraktur
      fonts:
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/eskapade_fraktur/EskapadeFraktur-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Playpen Sans
      fonts:
        - asset: assets/fonts/playpen_sans/PlaypenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/playpen_sans/PlaypenSans-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/playpen_sans/PlaypenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/playpen_sans/PlaypenSans-Bold.ttf
          weight: 700
          style: normal

    - family: Special Elite
      fonts:
        - asset: assets/fonts/special_elite/SpecialElite-Regular.ttf
          weight: 400
          style: normal

melos:
  useRootAsPackage: true

  scripts:
    clean:
      description: Limpa o projeto Flutter
      run: flutter clean

    get:
      description: Roda flutter pub get
      run: flutter pub get

    podsRepair:
      description: Repara pods do iOS
      run: |
        melos run clean
        cd ios && pod deintegrates
        cd ios && rm -rf Podfile.lock
        melos run get
        cd ios && pod install

    build:
      description: Build genérico
      run: flutter build

    buildBundle:
      description: Build AppBundle genérico
      run: flutter build appbundle

    buildApk:
      description: Build APK genérico
      run: flutter build apk

    buildIos:
      description: Build iOS genérico
      run: flutter build ios

    bundleProd:
      description: Build AppBundle produção
      run: flutter build appbundle --release --flavor prod --dart-define env=prod --dart-define-from-file=env/env_prod.json

    apkProd:
      description: Build APK produção
      run: flutter build apk --release --flavor prod --dart-define env=prod --dart-define-from-file=env/env_prod.json

    iosProd:
      description: Build iOS produção
      run: flutter build ios --release --flavor prod --dart-define env=prod --dart-define-from-file=env/env_prod.json

    ipaProd:
      description: Build IPA produção
      run: flutter build ipa --release --flavor prod --dart-define env=prod --dart-define-from-file=env/env_prod.json

    bundleQa:
      description: Build AppBundle QA
      run: flutter build appbundle --release --flavor qa --dart-define env=qa --dart-define-from-file=env/env_qa.json

    apkQa:
      description: Build APK QA
      run: flutter build apk --release --flavor qa --dart-define env=qa --dart-define-from-file=env/env_qa.json

    iosQa:
      description: Build iOS QA
      run: flutter build ios --release --flavor qa --dart-define env=qa --dart-define-from-file=env/env_qa.json

    ipaQa:
      description: Build IPA QA
      run: flutter build ipa --release --flavor qa --dart-define env=qa --dart-define-from-file=env/env_qa.json